### ISSUE TITLE
git install fails: syntax error: unknown group 'mlocate' in statoverride file

### ISSUE THREAD

**Issue by LorenzoPetite** [chef-cookbooks/git#105]
### Cookbook version

4.6.0
### Chef-client version

Chef 12.7.2
### Platform Details

AWS EC2: Ubuntu 14.04 fresh install
### Scenario:

Install git client on freshly booted ec2 instance
### Steps to Reproduce:

Boot a (fresh) instance in OpsWorks, with a setup recipe that runs
`git_client 'default' do
  action :install
end`
### Actual Result:

[2016-08-19T14:38:17+00:00] INFO: Processing apt_package[default :create git] action install (/var/chef/runs/20045579-685c-4541-8a4c-9250c8221a1e/local-mode-cache/cache/cookbooks/git/libraries/provider_git_client_package.rb line 14)
# 
# Error executing action 'install' on resource 'apt_package[default :create git]'
## Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install git=1:1.9.1-1ubuntu0.3 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
git-man liberror-perl
Suggested packages:
git-daemon-run git-daemon-sysvinit git-doc git-el git-email git-gui gitk
gitweb git-arch git-bzr git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
git git-man liberror-perl
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 3306 kB of archives.
After this operation, 21.9 MB of additional disk space will be used.
Get:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main liberror-perl all 0.17-1.1 [21.1 kB]
Get:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main git-man all 1:1.9.1-1ubuntu0.3 [699 kB]
Get:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main git amd64 1:1.9.1-1ubuntu0.3 [2586 kB]
Fetched 3306 kB in 0s (41.6 MB/s)
STDERR: dpkg: unrecoverable fatal error, aborting:
syntax error: unknown group 'mlocate' in statoverride file
E: Sub-process /usr/bin/dpkg returned an error code (2)
---- End output of apt-get -q -y install git=1:1.9.1-1ubuntu0.3 ----
Ran apt-get -q -y install git=1:1.9.1-1ubuntu0.3 returned 100
## Resource Declaration:

In /var/chef/runs/20045579-685c-4541-8a4c-9250c8221a1e/local-mode-cache/cache/cookbooks/git/libraries/provider_git_client_package.rb

14:           package "#{new_resource.name} :create #{parsed_package_name}" do
15:             package_name parsed_package_name
16:             version parsed_package_version
17:             action new_resource.package_action
18:             action :install
19:           end
20:         end
## Compiled Resource:

Declared in /var/chef/runs/20045579-685c-4541-8a4c-9250c8221a1e/local-mode-cache/cache/cookbooks/git/libraries/provider_git_client_package.rb:14:in `block in class:Package'

apt_package("default :create git") do
package_name "git"
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :package
cookbook_name "servu-stack"
end

**Comment by iennae** [comment]
Is this still a problem for you with the current version of the cookbook? Thanks.

**Comment by LorenzoPetite** [comment]
Sorry I don't know, we don't use this package any more.

**Comment by iennae** [comment]
Thanks for letting us know. I'll go ahead and close this for now and if it resurfaces as an issue for you, please do re-open.
