### ISSUE TITLE
documentation for git_client resource

### ISSUE THREAD

**Issue by giorgian** [chef-cookbooks/git#106]
### Cookbook version

5.0.0
### Chef-client version

N/A
### Platform Details

N/A
### Scenario:

How do I use the resource git_client? How do I tell it to install from source and not from package? The only piece of information provided by the doc is: `action :install`.
### Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
### Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]
### Actual Result:

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by borgified** [comment]
i was able to use it by putting this in my recipe
```
git_client 'default' do
  provider Chef::Provider::GitClient::Source
  source_checksum '1497001772f630d49809e981672edfe3e3ce1a1d18e905cd539c4d2f4dbcd75a'
  source_url 'https://www.kernel.org/pub/software/scm/git/git-2.13.3.tar.gz'
  source_version '2.13.3'
end
```

this is the resulting output
```
         * git_client[default] action install
         Recipe: build-essential::default
           * build_essential[install_packages] action install
             * yum_package[autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch] action install (up to date)
       (up to date)
           * yum_package[tar, expat-devel, gettext-devel, libcurl-devel, openssl-devel, perl-ExtUtils-MakeMaker, zlib-devel] action install (up to date)
           * remote_file[/tmp/kitchen/cache/git-2.13.3.tar.gz] action create
             - create new file /tmp/kitchen/cache/git-2.13.3.tar.gz
             - update content in file /tmp/kitchen/cache/git-2.13.3.tar.gz from none to 149700
             (new content is binary, diff output suppressed)
             - change mode from '' to '0644'
             - restore selinux security context
           * execute[Extracting and Building Git 2.13.3 from Source] action run
             - execute     (mkdir git-2.13.3 && tar -zxf git-2.13.3.tar.gz -C git-2.13.3 --strip-components 1)
          (cd git-2.13.3 && make prefix=/usr/local  install)
```

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by eheydrick** [comment]
@giorgian normally all you need is just the `action :install` to get an appropriate package for the platform you are on. If you want to install from source you can use the `source` provider like @borgified mentioned. You can also use the [source recipe](https://github.com/chef-cookbooks/git/blob/master/recipes/source.rb) and set attributes for the version you wish to install. I opened up #124 to document using `git_client` to install from source.
