### ISSUE TITLE
package_version doesn't install the specified version

### ISSUE THREAD

**Issue by darwin67** [chef-cookbooks/git#116]
### Cookbook version
6.0.0

### Chef-client version
12.18.31

### Platform Details
ubuntu 14 & 16

### Scenario:
Trying to install a specific version in Ubuntu

### Steps to Reproduce:
- create a dummy cookbook and only use ubuntu 16 as the platform
- create a attribute file and add the line `default['git']['package_version'] = '2.11.0'`
- add `git` cookbook as a dependency and add `include_recipe 'git'` in the default recipe
- converge in vagrant
- login and run `git --version`

### Expected Result:
2.11.0

### Actual Result:
2.7.4

## Comment
I've skimmed through the code and `package_version` is defined in the resource but it's never been passed a value. Is this the intended behaviour or is this just some outdated feature from 2 years ago?
https://github.com/chef-cookbooks/git/blame/master/README.md#L92

**Comment by cheeseplus** [comment]
The attribute`node['git']['package_version'] = '2.11.0'` isn't used by the default recipe - if you want to choose a version that isn't latest, use the resource directly as below

```
git_client 'default' do
  package_version '2.11.0'
  action :install
end
```

**Comment by darwin67** [comment]
well, that won't work and here's what i get if i try that.

![error](https://cloud.githubusercontent.com/assets/5746693/23679752/c0ee0d60-033d-11e7-899a-3229c604206f.png)

the default version in the Ubuntu repository is always a little old and almost never seems to be updated until the next major OS release.
in order to get the latest version of git, either you have to build it from source and install from a [ppa][ppa].

[ppa]: https://launchpad.net/~git-core/+archive/ubuntu/ppa?field.series_filter=xenial
