### ISSUE TITLE
git 6.1.0 seems to be broken with latest chef client?

### ISSUE THREAD

**Issue by EugenMayer** [chef-cookbooks/git#121]
### Cookbook version
6.1.0

### Chef-client version
chef_13.1.31

### Platform Details
debian 8.8.

### Scenario:
just trying to run chef

### Steps to Reproduce:
probably just deploy 6.1.0 as a cookbook and thats it

```
 Recipe Compile Error in /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb
 ================================================================================
 
 NoMethodError
 -------------
 undefined method `set' for Chef::Platform:Class
 
 Cookbook Trace:
 ---------------
   /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb:6:in `<top (required)>'
 
 Relevant File Content:
 ----------------------
 /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb:
 
   1:  # provider mappings for Chef 11
   2:  
   3:  #########
   4:  # client
   5:  #########
   6>> Chef::Platform.set platform: :amazon, resource: :git_client, provider: Chef::Provider::GitClient::Package
   7:  Chef::Platform.set platform: :centos, resource: :git_client, provider: Chef::Provider::GitClient::Package
   8:  Chef::Platform.set platform: :debian, resource: :git_client, provider: Chef::Provider::GitClient::Package
   9:  Chef::Platform.set platform: :fedora, resource: :git_client, provider: Chef::Provider::GitClient::Package
  10:  Chef::Platform.set platform: :mac_os_x, resource: :git_client, provider: Chef::Provider::GitClient::Osx
  11:  Chef::Platform.set platform: :redhat, resource: :git_client, provider: Chef::Provider::GitClient::Package
  12:  Chef::Platform.set platform: :scientific, resource: :git_client, provider: Chef::Provider::GitClient::Package
  13:  Chef::Platform.set platform: :smartos, resource: :git_client, provider: Chef::Provider::GitClient::Package
  14:  Chef::Platform.set platform: :solaris2, resource: :git_client, provider: Chef::Provider::GitClient::Package
  15:  Chef::Platform.set platform: :suse, resource: :git_client, provider: Chef::Provider::GitClient::Package
```

**Comment by EugenMayer** [comment]
i removed my Berkshelf.lock and rebuild the whole cookbook tree - then it started to work - does that make any sense?

**Comment by iennae** [comment]
@EugenMayer That makes sense. It means that the version of a cookbook was locked to a previous version of the cookbook that wasn't Chef 13 compliant. By clearing out the Berkshelf.lock it would pull down current versions that resolved the Chef 13 issue.

**Comment by erarunkumar** [comment]
Looks like i am getting below while running from chef DK v 2.0.28.
PS C:\Users\e3018705\chef-repo> knife job start chef-client indretest-1
C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- chef/rest (LoadError)
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/knife-push-1.0.2/lib/chef/knife/job_start.rb:27:in `block in <class:JobStart>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:232:in `block in load_deps'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:231:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:231:in `load_deps'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:216:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:275:in `load'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:275:in `<main>'

PS C:\Users\e3018705\chef-repo>

**Comment by iennae** [comment]
@erarunkumar please open a new issue in the appropriate github repository. It's unclear what this has to do with this specific git issue from your error message.
