### ISSUE TITLE
getting issue while installing git on a node from chefdk

### ISSUE THREAD

**Issue by erarunkumar** [chef-cookbooks/git#122]
### Cookbook version
6.1.0

### Chef-client version
chef-13.2.20

### Platform Details
centos7.3: nodes and chef server
windows 10 : chefDK

### Scenario:
trying to install git on a node from checkDK command prompt.

### Steps to Reproduce:
-ChefDK v2.0.28 on windows10
-chef server
   [root@indretest-0 ~]# rpm -qa|grep chef
   chef-manage-2.5.3-1.el7.x86_64
   chef-server-core-12.15.7-1.el7.x86_64
-installed the cookbook in chef-repo/cookbooks on chefkdk
-added the cookbook in runlist of the node
-tried to install git as below:
PS C:\Users\e3018705\chef-repo> knife job start chef-client indretest-1
C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- chef/rest (LoadError)
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/knife-push-1.0.2/lib/chef/knife/job_start.rb:27:in `block in <class:JobStart>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:232:in `block in load_deps'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:231:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:231:in `load_deps'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:216:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:275:in `load'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:275:in `<main>'

### Expected Result:
A version of git should get installed as the purpose of this cookbook 

### Actual Result:
getting exception as below:
PS C:\Users\e3018705\chef-repo> knife job start chef-client indretest-1
C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- chef/rest (LoadError)
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/knife-push-1.0.2/lib/chef/knife/job_start.rb:27:in `block in <class:JobStart>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:232:in `block in load_deps'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:231:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:231:in `load_deps'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/knife.rb:216:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:275:in `load'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:275:in `<main>'

**Comment by iennae** [comment]
This should be fixed in a current version of chefdk. If after upgrading chefdk you are still having this problem, please reopen.

Thanks.
