### ISSUE TITLE
Checkout modifies mtimes

### ISSUE THREAD

**Issue by axos88** [chef-cookbooks/git#127]
### Cookbook version
6.1.0

### Chef-client version
12.19.36

### Platform Details
Linux/debian

### Scenario:

Checkout on an existing repo modifies mtimes in the directory

```
  git site.www_root do
    repository "..."
    revision "#{new_resource.version}-branch"
    user new_resource.owner
    group new_resource.group
    depth 1

    action :checkout
  end
```

### Steps to Reproduce:

1. Run cookbook once to create a checkout
2. Modify some files in the directory, and add a few unversioned ones
3. Rerun cookbook

### Expected Result:

No action, all files' mtimes stay the same

### Actual Result:

No action, but mtimes are changed to the time the cookbook was run the second time

**Comment by tas50** [comment]
@axos88 The git resource isn't actually part of this cookbook. It's a built in resource within the chef-client itself. You'll want to file this same issue in the Chef repo.
