### ISSUE TITLE
Basic git authentication support needed for Windows environments

### ISSUE THREAD

**Issue by joshburt** [chef-cookbooks/git#51]
Windows Chef Developer Here.  All our systems are Windows (client, server, source control, CI, etc - everything).

The primary Windows-centric source control systems (TFS2013 and Visual Studio Online) do not support ssh keys and only support the use of oAuth or username/password for git repositories.  

Without support for basic authentication features in this git cookbook, the use of git within Windows-centric environments with enterprise class development systems is not possible.

Thanks!

**Comment by eelkram** [comment]
I second this.  We also need support for Visual Studio Online.

**Comment by cogmation** [comment]
:+1:

**Comment by iennae** [comment]
This cookbook installs a git client on Windows. What are you looking for beyond that? Do you have ideas about how it could be implemented?

**Comment by iennae** [comment]
@joshburt I'm going to go ahead and close this. If you folks have ideas about how this could be implemented, please do reopen with your thoughts.

Thanks!
