### ISSUE TITLE
Windows Installation needs updated to use Git for Windows

### ISSUE THREAD

**Issue by kbaltrinic** [chef-cookbooks/git#78]
The windows installation is still using msysgit 1.9.5 which is now deprecated (Per https://github.com/msysgit/msysgit/commit/088d25f31e34544c90a3c3f7342ea424333f2805).  The current release of [Git for Windows](https://github.com/git-for-windows/git/releases/tag/v2.5.0.windows.1) is v 2.5.

**Comment by vinyar** [comment]
https://github.com/jssjr/git/pull/80
if you have a vagrant file locally, would you mind testing it? @kbaltrinic

**Comment by kbaltrinic** [comment]
Sorry I never got around to testing, but I see its been merged.  Thanks for the quick turnaround.

**Comment by iennae** [comment]
Thanks for confirming @kbaltrinic. Closing this issue.
