### ISSUE TITLE
Multiple Problems with non/default Windows Git Installation

### ISSUE THREAD

**Issue by kbaltrinic** [chef-cookbooks/git#84]
I am attempting to install Git for Windows 2.6.3 x64 with this cookbook and have encountered numerous problems.

First I attempted the following:

```ruby
# My attributes/default.rb:
override['git']['version'] = '2.6.3'
override['git']['architecture'] = '64'
override['git']['url'] = "https://github.com/git-for-windows/git/releases/download/v#{node['git']['version']}.windows.1/Git-#{node['git']['version']}-#{node['git']['architecture']}-bit.exe"
override['git']['checksum'] = 'da1ce21bbaf1dcfd0a8c14e37cedc2d7a0948d01b69efbecbf8eb12fe91c3549'
override['git']['display_name'] = "Git version #{node['git']['version']}"
```

Then:
```ruby
# My recipes/default.rb:
include_recipe 'git'
```

This didn't work.  Digging through the cookbook code I discovered that the above attributes are only honored by the `git::windows` recipe.  When the default recipe is invoked, hardcoded defaults from the [helper.rb file](https://github.com/jssjr/git/blob/v4.3.4/libraries/helpers.rb) seem to be what gets used.

I updated my recipe to invoke the `git::windows` recipe.  This did not work because the [windows recipe](https://github.com/jssjr/git/blob/v4.3.4/recipes/windows.rb) is incorrectly looking at `['windows']['url']` instead of `['git']['url']`, and similarly for the other attributes.

I worked around this by directly calling the `git_client` resource with the correct attributes.  This at least successfully installed the software.

However, where is a further issue wherein installing 64-bit git is not correctly supported.  The path variable is updated to point to the 32 bit install location because [`Program Files (x86)` is used any time its exists](https://github.com/jssjr/git/blob/master/libraries/provider_git_client_windows.rb#L19), regardless of the bit-ness of the version being installed.

Rather than just enumerating these issues, I am considering submitting a PR but I am not quite sure what would be considered the right solution to some of this.  In particular for the first problem, given my choice, I would get rid of the `windows` recipe all together and simply update the `package` recipe to invoke the git_client resource for windows just as it does for mac.  But maybe I am missing something there?

**Comment by iennae** [comment]
This is an issue with the derived attributes. 

Set in your attributes these variables explicitly and without having them derived at compile time:

+  default['git']['url'] = 'https://github.com/git-for-windows/git/releases/download/v2.7.0.windows.1/Git-2.7.0-32-bit.exe'
 +  default['git']['checksum'] = '58d7b7b8038e91ac6a29c3d9150da536f836247dafde4821c745ba1f88ccc0f1'
 +  default['git']['display_name'] = "Git version 2.7.0 32-bit"
is an example of setting them explicitly rather than deriving them. 

Please reopen this issue if that doesn't resolve your problem.

**Comment by iennae** [comment]
Totally updated the wrong issue here, was looking at multiple issues. You also pointed out an issue with the provider, so reopening.

**Comment by iennae** [comment]
Based on this comment:
      # Git is installed to Program Files (x86) on 64-bit machines and
          # 'Program Files' on 32-bit machines

it looks like it's intentionally getting installed to ProgramFiles(x86).  Where should it get installed?

**Comment by iennae** [comment]
You are using an older version of the cookbook, release v4.3.5 and v4.3.6 have some fixes that might have helped out some. About to release 4.3.7 that will fix some of the attribute precedence issues.

Thanks for reporting this issue. Gave me a lot to dig into about the cookbook.
