### ISSUE TITLE
64-bit Git Install Incorrectly Updates Path On Windows

### ISSUE THREAD

**Issue by joshburt** [chef-cookbooks/git#91]
There are 64-bit builds of Git.  The current cookbook does not handle this.

**Steps to reproduce**

Set the version to download as such:
```
    "git": {
      "version": "2.7.2.windows.1",
      "checksum": "ec4009b36ce855ab262f999030fff5471de73cf0071202138d395648756c7e8b",
      "url": "https://github.com/git-for-windows/git/releases/download/v2.7.2.windows.1/Git-2.7.2-64-bit.exe",
      "display_name": "Git version 2.7.2"
    }

```

The PATH is incorrectly updated to use the (x86) path erroneously on windows.  This makes all future calls to git fail.

**Comment by iennae** [comment]
This is intentionally being done by the provider right now:

          # Git is installed to Program Files (x86) on 64-bit machines and
          # 'Program Files' on 32-bit machines
          PROGRAM_FILES = ENV['ProgramFiles(x86)'] || ENV['ProgramFiles']
          GIT_PATH = "#{PROGRAM_FILES}\\Git\\Cmd".freeze

What should the path be? 

Thanks for helping us debug this!

**Comment by joshburt** [comment]
There is no single default location.  This is determined by the git installer (and the bitness of the package).  

If a 32-bit version is installed it’s placed in C:\Program Files (x86)\Git
If a 64-bit version is installed it’s placed in C:\Program Files\Git

Since there is not an easy way to determine the install location (that I’m aware of) under this scenario I have been brain storming and have some suggestions to bounce off you:

- **Registry Based**

Parse it out of the registry post install.  It looks like this might be a possible place to extract it from:
```
Registry key: HKEY_CLASSES_ROOT\Directory\background\shell\git_shell\command
Value when 32-bit: "C:\Program Files (x86)\Git\git-bash.exe" "--cd=%v."
Value when 64-bit: "C:\Program Files\Git\git-bash.exe" "--cd=%v."
```

There could possibly be other registry keys that will work as well.  Using a tool like Process Monitor https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx during install could provide a list.

- **Filename Based**: Parse the installer executable filename and attempt to determine the bitness
- **Attribute Driven**: Create an attribute ‘flag’ that designates bitness and enforces this artificially




With the advent of Windows Core & Nano and the effort to create 64-bit builds of the Chef client we ultimately need to have 64-bit support of the tools we use along-side Chef as well.

Thanks!

**Comment by smurawski** [comment]
Here are the challenges.. MSI's don't always broadcast changes to path (when reboots are pending on the box for example).  Also, not every top level program listens for changes to the path, which is why if we want to find git later in the course of the chef client run, we need to update the path as ruby sees it, so any ruby code or child shell outs will get it.

If the cookbook is picking the installer, it can know which path to put things on more easily.  However, it shouldn't be too hard to figure out.. we could test program files x86 and program files and see where the git.exe landed, then put that on the path.  I can work up a PR early next week most likely.

**Comment by iennae** [comment]
@smurawski any progress on this? :) Thanks!

**Comment by smurawski** [comment]
@iennae @joshburt I just submitted a PR to add support for installing the 64 bit git client and finding the right path.

**Comment by iennae** [comment]
@joshburt Please check out cookbook version 4.4.1. Reopen if this doesn't solve the problem. Again thank you for submitting the original issue and sharing the underlying problems to improve my context with the issue. We really appreciate your help in making community cookbooks awesome!
