### ISSUE TITLE
No resource or method named `git_client' for `Chef::Recipe "package"'

### ISSUE THREAD

**Issue by starx** [chef-cookbooks/git#94]
Using in vagrant context with `chef_solo`

>  Cookbook Trace:
> ==> default: ---------------
> ==> default:   /tmp/vagrant-chef/8573ad60a7ce2c764a8ed5706df9f94d/cookbooks/git/recipes/package.rb:34:in `from_file'
> ==> default:   /tmp/vagrant-chef/8573ad60a7ce2c764a8ed5706df9f94d/cookbooks/git/recipes/default.rb:19:in`from_file'
> ==> default:   /tmp/vagrant-chef/8573ad60a7ce2c764a8ed5706df9f94d/cookbooks/zsh/recipes/oh_my_zsh.rb:17:in `from_file'
> ==> default: Relevant File Content:
> ==> default: ----------------------
> ==> default: /tmp/vagrant-chef/8573ad60a7ce2c764a8ed5706df9f94d/cookbooks/git/recipes/package.rb:
> ==> default:  27:      osx_dmg_url node['git']['osx_dmg']['url']
> ==> default:  28:      osx_dmg_checksum node['git']['osx_dmg']['checksum']
> ==> default:  29:      action :install
> ==> default:  30:    end
> ==> default:  31:  when 'windows'
> ==> default:  32:    include_recipe 'git::windows'
> ==> default:  33:  else
> ==> default:  34>>   git_client 'default' do
> ==> default:  35:      action :install
> ==> default:  36:    end
> ==> default:  37:  end
> ==> default:  38:

**Comment by iennae** [comment]
Hi,

There isn't enough information in this issue to provide us what we need to help you debug your problem here. What I can surmise based on the error message is that you aren't trying to use the package recipe on Mac OS X or Windows. Can you provide more information about what your platform is? (What version of what OS, etc.) Thanks!

**Comment by starx** [comment]
@iennae Yes, I am trying to spin up a linux VM using Chef on Windows OS. What other information I can provide, please let me know?

**Comment by iennae** [comment]
@starx can you provide information about how you are spinning up the linux vm? Can you provide the full error that you are getting back. Right now you haven't provided enough of the error or the way that you are using the recipe. Thanks!

**Comment by Sauraus** [comment]
@starx by the looks of it you are trying to spin up an OS X VM on Windows, which is fine provided you are using VMWare and not VirtualBox.

Furthermore there was a bug in the cookbook that prevented the DMG/PKG installation on OS X which was resolved with this pull request: https://github.com/chef-cookbooks/git/pull/98

**Comment by starx** [comment]
No it is Ubuntu 14.04 64bit on virtual box as Windows 10 as guest.

**Comment by Sauraus** [comment]
Ok we need more details? Are you running a kitchen converge or test? Or is this in a wrapper cookbook?

**Comment by tas50** [comment]
Closing this out unless we can get a full chef-client log of the failure and a detailed set of details on the configuration being used.
